spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopstack}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Nithin@123}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# Security debug/dev configuration
shopstack.jwt.secret=${SHOPSTACK_JWT_SECRET:9a67471ec635249314b81c2f306915a1f6a4a0342938a14b5334c9c8695d73af9a67471ec635249314b81c2f306915a1f6a4a0342938a14b5334c9c8695d73af}
shopstack.jwt.expiration=${SHOPSTACK_JWT_EXPIRATION:86400000}

# Email SMTP Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


